export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const SAVE_PRODUCT = "SAVE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const SHOW_PRODUCT = "SHOW_PRODUCT";
export const RESET_PRODUCT_TO_SHOW = "RESET_PRODUCT_TO_SHOW";